package:
  name: species_proteins
  version: 0.0.1
channels:
  - conda-forge
  - bioconda
  - defaults
requirements:
  build:
    - python=3.8
    - setuptools
  run:
    - python=3.8
    - future>=0.18.2
    - cwltool>=3.0
    - bioservices>=1.7.7
    - click>=7.1.2
test:
  imports:
  -  species_proteins

source:
  path: ../